---
  - name: Deploy telegram bot GuessMu 3.0.
    hosts: all
    become: yes

    vars_files:
      - vars/api_config.yml
      - vars/install_config.yml
      
    tasks:
      - name: Download git repository.
        git:
            repo: https://github.com/ihnashchenka/TelegramBot.git
            dest: "{{ install_dir }}/{{ module_name }}"
            force: yes
            
        #todo: possibly include to git task 
    #  - name: Change access mode for bot sources.  
    ##    file:
    #        path:  "{{ install_dir }}/{{ module_name }}"
    #        state: directory
    #        mode: u=rwx,g=rx,o=rx
    #        recurse: yes
          
      - name: Install libpq-dev to build libs for PostgreSQL.
        apt:
            name: libpq-dev
            update_cache: yes 
                
      - name: Install pip.
      
        apt:
            name: python3-pip
            update_cache: yes
            
      - name: Install python packages from requirenment.txt.
        pip:
            requirements: "{{ install_dir }}/{{ module_name }}/requirements.txt"
          
      - name: Create log directory.
        file:
            path: "{{ log_path }}/{{ module_name }}"
            state: directory
            
        #todo: do cleanup with archiving to ...log.1
      - name: Create log files.
        file:
            path: "{{ item }}"
            state: touch
        with_items:
        - "{{ log_path }}/{{ module_name }}/{{ stdout_filename }}"
        - "{{ log_path }}/{{ module_name }}/{{ stderr_filename }}"
        
      - name: Create bot service file.
        copy:
            dest: "{{ service_dir }}/{{ module_name }}.service"
            content: |
                [Service]
                ExecStart={{ python_dir }} {{ install_dir }}/{{ module_name }}/bot.py
                Environment=TELEGRAM_TOKEN={{  TELEGRAM_TOKEN  }}
                Environment=DATABASE_URL={{  DATABASE_URL  }}
                StandardOutput=file:{{ log_path }}/{{ module_name }}/{{ stdout_filename }}
                StandardError=file:{{ log_path }}/{{ module_name }}/{{ stderr_filename }}
                [Install]
                WantedBy=multi-user.target
                
        #todo: check if it is restarted
      - name: Start the bot.
        service:
            name: "{{ module_name }}"
            state: restarted
    